image: node:16

before_script:
  - yarn

cache:
  paths:
    - node_modules

pages:
  script:
    - yarn build && yarn export
    - mv out/* public/
    - rm -rf out
  artifacts:
    paths:
      - public
  only:
    - scoreboard
