image: node

before_script:
  - npm install -g yarn
  - yarn

cache:
  paths:
    - node_modules

pages:
  script:
    - yarn build && yarn export
  artifacts:
    paths:
      - out
  only:
    - scoreboard
