version: "3"

services:
  support:
    build:
      context: ./challenge/support
    ports:
      - 6969:6969
  web:
    build:
      context: ./challenge/web
    depends_on:
      - support
    ports:
      - 1337:1337
  # app:
  #   build:
  #     context: ./challenge/app
  #   depends_on:
  #     - web
