version: "3.7"
services:
    php:
        build:
            context: ./problem/php
        image: catalog_php:latest
	dns: 
            - 8.8.8.8
        ports:
            - 443:443
        environment:
            MYSQL_HOST: "mysql"
            MYSQL_DATABASE: "comic_catalog"
            MYSQL_USER: "mysql"
            MYSQL_PASSWORD: "mJ5kcbZc6UC7N2A@153"
            RECAPTCHA_SECRET: "hmm"
        volumes:
            - "./problem/php/src:/var/www/html"
        restart: always
    mysql:
        build:
            context: ./problem/mysql
        image: catalog_mysql:latest
        environment:
            MYSQL_DATABASE: "comic_catalog"
            MYSQL_USER: "mysql"
            MYSQL_PASSWORD: "mJ5kcbZc6UC7N2A@153"
            MYSQL_ROOT_PASSWORD: "GdtQ3LjuW7myeC3@123"
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "./problem/mysql-data:/var/lib/mysql"
    bot:
        deploy:
            replicas: 1
        build:
            context: ./problem/bot
        image: catalog_bot:latest
        environment:
            BASE_URL: "https://bettercatalog.xyz"
            MYSQL_HOST: "mysql"
            MYSQL_DATABASE: "comic_catalog"
            MYSQL_USER: "mysql"
            MYSQL_PASSWORD: "mJ5kcbZc6UC7N2A@153"
        depends_on:
            - mysql
        restart: always
        cap_add:
            - SYS_ADMIN
