name: GitHub Pages

on:
  push:
    branches:
      - scoreboard
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.2.0
        
      - name: yarn install --frozen-lockfile
        run: yarn install --frozen-lockfile

      - name: yarn build && yarn export
        run: yarn build && yarn export

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          
